<?php
/**
 * Register and output open graph tags, Twitter cards, custom color CSS, and the icon fonts.
 *
 * @package   SocialWarfare\Functions
 * @copyright Copyright (c) 2016, Warfare Plugins, LLC
 * @license   GPL-3.0+
 * @since     1.0.0
 */

defined( 'WPINC' ) || die;

/**
 *  Queue up our hook function which will in turn call all of Social Warfare's custom hooks
 */
add_action( 'wp_head'           , 'swp_add_header_meta'      , 1 );
add_filter( 'swp_header_values' , 'swp_open_graph_values'    , 5 );
add_filter( 'swp_header_values' , 'swp_twitter_card_values'  , 10 );
add_filter( 'swp_header_html'   , 'swp_open_graph_html'      , 5 );
add_filter( 'swp_header_html'   , 'swp_twitter_card_html'    , 10 );
add_filter( 'swp_header_html'   , 'swp_output_custom_color'  , 15 );
add_filter( 'swp_header_html'   , 'swp_output_font_css'      , 20 );
add_action( 'admin_head'        , 'swp_output_font_css'      , 20 );

/**
 * The function that we're hooking into the header
 *
 * All other items being added to the header will be hooked into
 * swp_meta_tags which we will call and print via this function.
 *
 * @since 1.4.0
 * @access public
 * @param  none
 * @return none
 */
function swp_add_header_meta() {

	// Get the global options and the post ID
	global $swp_user_options;
	$info['postID'] = get_the_ID();
	$info['html_output'] = '';

	/**
	 * Create and return the values to be used in the header meta tags
	 *
	 * All meta values will be returned in the $info['meta_tag_values'] array.
	 *
	 * The following values will be returned from the function swp_open_graph_values():
	 * Open Graph Type          $info['meta_tag_values']['og_type']
	 * Open Graph Title         $info['meta_tag_values']['og_title']
	 * Open Graph Description   $info['meta_tag_values']['og_description']
	 * Open Graph Image         $info['meta_tag_values']['og_image']
	 * Open Graph Image Width   $info['meta_tag_values']['og_image_width']
	 * Open Graph Image Height  $info['meta_tag_values']['og_image_height']
	 * Open Graph URL           $info['meta_tag_values']['og_url']
	 * Open Graph Site Name     $info['meta_tag_values']['og_site_name']
	 * Article Author           $info['meta_tag_values']['article_author']
	 * Article Publisher        $info['meta_tag_values']['article_publisher']
	 * Article Published Time   $info['meta_tag_values']['article_published_time']
	 * Article Modified Time    $info['meta_tag_values']['article_modified_time']
	 * OG Modified Time         $info['meta_tag_values']['og_modified_time']
	 * Facebook App ID          $info['meta_tag_values']['fb_app_id']
	 *
	 * The following values will be returned from the function swp_twitter_card_values():
	 * Twitter Card type        $info['meta_tag_values']['twitter_card']
	 * Twitter Title            $info['meta_tag_values']['twitter_title']
	 * Twitter Description      $info['meta_tag_values']['twitter_description']
	 * Twitter Image            $info['meta_tag_values']['twitter_image']
	 * Twitter Site             $info['meta_tag_values']['twitter_site']
	 * Twitter creator          $info['meta_tag_values']['twitter_creator']
	 *
	 * @since 2.1.4
	 * @access public
	 * @var array $info An array of information
	 * @return array $info The modified array with the 'meta_tag_values' index populated
	 */
	$info = apply_filters( 'swp_header_values' , $info );

	/**
	 * A filter to take the values from above and compile them into their html format
	 *
	 * This filter will take the values from $info['meta_tag_values'] and compile
	 * them into html stored in the $info['html_output'] index. This index will be
	 * a string that gets added to by each hook (.=), not an array.
	 *
	 * Note: Each meta tag should end with PHP_EOL for clean structured HTML output
	 *
	 * @since 2.1.4
	 * @access public
	 * @var array $info An array of information
	 * @return array $info The modified array with the 'html_output' index populated.
	 */
	$info = apply_filters( 'swp_header_html' , $info );

	if ( $info['html_output'] ) :
		echo PHP_EOL . '<!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare v' . SWP_VERSION . ' http://warfareplugins.com -->';
		echo $info['html_output'];
		echo PHP_EOL . '<!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare v' . SWP_VERSION . ' http://warfareplugins.com -->' . PHP_EOL . PHP_EOL;
	endif;
}

/**
 * Open Graph Meta Tag Values
 *
 * Notes: If the user specifies an Open Graph tag,
 * we're going to develop a complete set of tags. Order
 * of preference for each tag is as follows:
 * 1. Did they fill out our open graph field?
 * 2. Did they fill out Yoast's social field?
 * 3. Did they fill out Yoast's SEO field?
 * 4. We'll just auto-generate the field from the post.
 *
 * @since  2.1.4
 * @access public
 * @param  array $info An array of data about the post
 * @return array $info The modified array
 */
function swp_open_graph_values($info){

	global $swp_user_options;

	/**
	 * Begin by fetching the user's default custom settings
	 *
	 */
	$custom_og_title        = htmlspecialchars( get_post_meta( $info['postID'] , 'nc_ogTitle' , true ) );
	$custom_og_description  = htmlspecialchars( get_post_meta( $info['postID'] , 'nc_ogDescription' , true ) );
	$custom_og_image_id     = get_post_meta( $info['postID'] , 'nc_ogImage' , true );
	$custom_og_image_url    = get_post_meta( $info['postID'] , 'swp_open_graph_image_url' , true );
	$custom_og_image_data   = json_decode( get_post_meta( $info['postID'] , 'swp_open_graph_image_data' , true ) );

	/**
	 * Open Graph Tags (The Easy Ones That Don't Need Conditional Fallbacks)
	 *
	 */
	$info['meta_tag_values']['og_url']                  = get_permalink();
	$info['meta_tag_values']['og_site_name']            = get_bloginfo( 'name' );
	$info['meta_tag_values']['og_type']                 = 'article';
	$info['meta_tag_values']['article_published_time']  = get_post_time( 'c' );
	$info['meta_tag_values']['article_modified_time']   = get_post_modified_time( 'c' );
	$info['meta_tag_values']['og_modified_time']        = get_post_modified_time( 'c' );

	/**
	 * Disable Jetpack's Open Graph tags
	 *
	 */
	add_filter( 'jetpack_enable_opengraph', '__return_false', 99 );
	add_filter( 'jetpack_enable_open_graph', '__return_false', 99 );

	/**
	 * Check for and coordinate with Yoast to create the best possible values for each tag
	 *
	 */
	if ( defined( 'WPSEO_VERSION' ) ) :
		global $wpseo_og;
		$yoast_og_setting = has_action( 'wpseo_head', array( $wpseo_og, 'opengraph' ) );
	else :
		$yoast_og_setting = false;
	endif;

	// Check if the user has filled out at least one of the custom fields
	if ( defined( 'WPSEO_VERSION' ) && ( !empty( $custom_og_title ) || !empty( $custom_og_description ) || !empty( $custom_og_image ) ) ):

		/**
		 * YOAST SEO: It rocks, so if it's installed, let's coordinate with it
		 *
		 */

		// Collect their Social Descriptions as backups if they're not defined in ours
		$yoast_og_title         = get_post_meta( $info['postID'] , '_yoast_wpseo_opengraph-title' , true );
		$yoast_og_description   = get_post_meta( $info['postID'] , '_yoast_wpseo_opengraph-description' , true );
		$yoast_og_image         = get_post_meta( $info['postID'] , '_yoast_wpseo_opengraph-image' , true );
		$yoast_seo_title        = get_post_meta( $info['postID'] , '_yoast_wpseo_title' , true );
		$yoast_seo_description  = get_post_meta( $info['postID'] , '_yoast_wpseo_metadesc' , true );

		// Cancel their output if ours have been defined so we don't have two sets of tags
		global $wpseo_og;
		remove_action( 'wpseo_head', array( $wpseo_og, 'opengraph' ), 30 );

		// Fetch the WPSEO_SOCIAL Values
		$wpseo_social = get_option( 'wpseo_social' );

	// End of the Yoast Conditional
	endif;

	/**
	 *  Open Graph Title: Create an open graph title meta tag
	 *
	 */
	if ( $custom_og_title ) :
		$info['meta_tag_values']['og_title'] = $custom_og_title;
	elseif ( !empty( $yoast_og_title )) :
		$info['meta_tag_values']['og_title'] = $yoast_og_title;
	elseif ( !empty( $yoast_seo_title ) ) :
		$info['meta_tag_values']['og_title'] = $yoast_seo_title;
	else :
		$info['meta_tag_values']['og_title'] = trim( convert_smart_quotes( htmlspecialchars_decode( get_the_title() ) ) );
	endif;

	/**
	 * Open Graph Description
	 *
	 */
	if ( $custom_og_description ) :
		$info['meta_tag_values']['og_description'] = $custom_og_description;
	elseif ( !empty( $yoast_og_description ) ) :
		$info['meta_tag_values']['og_description'] = $yoast_og_description;
	elseif ( !empty( $yoast_seo_description ) ) :
		$info['meta_tag_values']['og_description'] = $yoast_seo_description;
	else :
		$info['meta_tag_values']['og_description'] = convert_smart_quotes( htmlspecialchars_decode( swp_get_excerpt_by_id( $info['postID'] ) ) ) ;
	endif;

	/**
	 * Open Graph image
	 *
	 */
	if ( $custom_og_image_url ) :
		$info['meta_tag_values']['og_image'] = $custom_og_image_url;
	elseif ( !empty( $yoast_og_image ) ) :
		$info['meta_tag_values']['og_image'] = $yoast_og_image;
	else :
		$thumbnail_url = get_post_meta( $info['postID'] , 'swp_open_thumbnail_url' , true );
		if ( $thumbnail_url ) :
			$info['meta_tag_values']['og_image'] = $thumbnail_url;
		endif;
	endif;

	/**
	 * Open Graph Image Dimensions
	 *
	 */
	if ( !empty( $custom_og_image_data ) ) :
		$info['meta_tag_values']['og_image_width'] 	= $custom_og_image_data[1];
		$info['meta_tag_values']['og_image_height']	= $custom_og_image_data[2];
	endif;

	/**
	 * Facebook Author
	 *
	 */
	if ( get_the_author_meta( 'swp_fb_author' , swp_get_author( $info['postID'] ) ) ) :
		$info['meta_tag_values']['article_author'] = get_the_author_meta( 'swp_fb_author' , swp_get_author( $info['postID'] ) );
	elseif ( get_the_author_meta( 'facebook' , swp_get_author( $info['postID'] ) ) && defined( 'WPSEO_VERSION' ) ) :
		$info['meta_tag_values']['article_author'] = get_the_author_meta( 'facebook' , swp_get_author( $info['postID'] ) );
	endif;

	/**
	 * Open Graph Publisher
	 *
	 */
	if ( !empty( $swp_user_options['facebookPublisherUrl'] )) :
		$info['meta_tag_values']['article_publisher'] = $swp_user_options['facebookPublisherUrl'];
	elseif ( isset( $wpseo_social ) && !empty( $wpseo_social['facebook_site'] ) ) :
		$info['meta_tag_values']['article_publisher'] = $wpseo_social['facebook_site'];
	endif;

	/**
	 * Open Graph App ID
	 *
	 */
	if ( !empty( $swp_user_options['facebookAppID'] ) ) :
		$info['meta_tag_values']['fb_app_id'] = $swp_user_options['facebookAppID'];
	elseif ( isset( $wpseo_social ) && !empty( $wpseo_social['fbadminapp'] ) ) :
		$info['meta_tag_values']['fb_app_id'] = $wpseo_social['fbadminapp'];
	else :
		$info['meta_tag_values']['fb_app_id'] = '529576650555031';
	endif;

	return $info;
}

function swp_open_graph_html($info) {

	$info['html_output'] .= PHP_EOL . '<meta property="og:type" content="'.$info['meta_tag_values']['og_type'].'" />';
	$info['html_output'] .= PHP_EOL . '<meta property="og:title" content="'.$info['meta_tag_values']['og_title'].'" />';
	$info['html_output'] .= PHP_EOL . '<meta property="og:description" content="'.$info['meta_tag_values']['og_description'].'" />';

	if( isset( $info['meta_tag_values']['og_image'] ) ):
		$info['html_output'] .= PHP_EOL . '<meta property="og:image" content="'.$info['meta_tag_values']['og_image'].'" />';
		$info['html_output'] .= PHP_EOL . '<meta property="og:image:width" content="'.$info['meta_tag_values']['og_image_width'].'" />';
		$info['html_output'] .= PHP_EOL . '<meta property="og:image:height" content="'.$info['meta_tag_values']['og_image_height'].'" />';
	endif;

	$info['html_output'] .= PHP_EOL . '<meta property="og:url" content="'.$info['meta_tag_values']['og_url'].'" />';
	$info['html_output'] .= PHP_EOL . '<meta property="og:site_name" content="'.$info['meta_tag_values']['og_site_name'].'" />';

	if( isset( $info['meta_tag_values']['article_author'] ) ):
		$info['html_output'] .= PHP_EOL . '<meta property="article:author" content="'.$info['meta_tag_values']['article_author'].'" />';
	endif;

	if( isset( $info['meta_tag_values']['article_publisher'] ) ):
		$info['html_output'] .= PHP_EOL . '<meta property="article:publisher" content="'.$info['meta_tag_values']['article_publisher'].'" />';
	endif;

	$info['html_output'] .= PHP_EOL . '<meta property="article:published_time" content="'.$info['meta_tag_values']['article_published_time'].'" />';
	$info['html_output'] .= PHP_EOL . '<meta property="article:modified_time" content="'.$info['meta_tag_values']['article_modified_time'].'" />';
	$info['html_output'] .= PHP_EOL . '<meta property="og:updated_time" content="'.$info['meta_tag_values']['og_modified_time'].'" />';
	$info['html_output'] .= PHP_EOL . '<meta property="fb:app_id" content="'.$info['meta_tag_values']['fb_app_id'].'" />';

	return $info;
}

/**
 *  Generate the Twitter Card fields
 *
 *	Notes: If the user has Twitter cards turned on, we
 *	need to generate them, but we also like Yoast so we'll
 *	pay attention to their settings as well. Here's the order
 *	of preference for each field:
 *	1. Did the user fill out the Social Media field?
 *	2. Did the user fill out the Yoast Twitter Field?
 *	3. Did the user fill out the Yoast SEO field?
 *	4. We'll auto generate something logical from the post.
 *
 * @since 2.1.4
 * @access public
 * @param array $info An array of information about the post
 * @return array $info The modified array
 */
function swp_twitter_card_values($info) {

	global $swp_user_options;

	if ( is_singular() && $swp_user_options['swp_twitter_card'] ) :

		/**
		 * Begin by fetching the user's default custom settings
		 *
		 */
		$custom_og_title        = htmlspecialchars( get_post_meta( $info['postID'] , 'nc_ogTitle' , true ) );
		$custom_og_description  = htmlspecialchars( get_post_meta( $info['postID'] , 'nc_ogDescription' , true ) );
		$custom_og_image_id     = get_post_meta( $info['postID'] , 'nc_ogImage' , true );
		$custom_og_image_url    = get_post_meta( $info['postID'] , 'swp_open_graph_image_url' , true );
		$user_twitter_handle    = get_post_meta( $info['postID'] , 'swp_twitter_username' , true );

		/**
		 * YOAST SEO: It rocks, so if it's installed, let's coordinate with it
		 *
		 */
		if ( defined( 'WPSEO_VERSION' ) ) :
			$yoast_twitter_title        = get_post_meta( $info['postID'] , '_yoast_wpseo_twitter-title' , true );
			$yoast_twitter_description  = get_post_meta( $info['postID'] , '_yoast_wpseo_twitter-description' , true );
			$yoast_twitter_image        = get_post_meta( $info['postID'] , '_yoast_wpseo_twitter-image' , true );
			$yoast_seo_title            = get_post_meta( $info['postID'] , '_yoast_wpseo_title' , true );
			$yoast_seo_description      = get_post_meta( $info['postID'] , '_yoast_wpseo_metadesc' , true );

			// Cancel their output if ours have been defined so we don't have two sets of tags
			remove_action( 'wpseo_head' , array( 'WPSEO_Twitter', 'get_instance' ) , 40 );
		endif;

		/**
		 * JET PACK: If ours are activated, disable theirs
		 *
		 */
		add_filter( 'jetpack_disable_twitter_cards', '__return_true', 99 );

		/**
		 * TWITTER TITLE
		 *
		 */
		if ( $custom_og_title ):
			$info['meta_tag_values']['twitter_title'] = $custom_og_title;
		elseif( !empty( $yoast_twitter_title ) ) :
			$info['meta_tag_values']['twitter_title'] = $yoast_twitter_title;
		else:
			$info['meta_tag_values']['twitter_title'] = $info['meta_tag_values']['og_title'];
		endif;

		/**
		 * TWITTER DESCRIPTION
		 *
		 */
		if( $custom_og_description ):
			$info['meta_tag_values']['twitter_description'] = $custom_og_description;
		elseif ( !empty( $yoast_twitter_description ) ) :
			$info['meta_tag_values']['twitter_description'] = $yoast_twitter_description;
		else:
			$info['meta_tag_values']['twitter_description'] = $info['meta_tag_values']['og_description'];
		endif;

		/**
		 * TWITTER IMAGE
		 *
		 */
		if ( $custom_og_image_url ):
			$info['meta_tag_values']['twitter_image'] = $custom_og_image_url;
		elseif ( !empty( $yoast_twitter_image ) ) :
			$info['meta_tag_values']['twitter_image'] = $yoast_twitter_image;
		elseif($info['meta_tag_values']['og_image']):
			$info['meta_tag_values']['twitter_image'] = $info['meta_tag_values']['og_image'];
		endif;

		/**
		 * The Twitter Card Type
		 *
		 */
		if($info['meta_tag_values']['twitter_image']):
			$info['meta_tag_values']['twitter_card'] = 'summary_large_image';
		else:
			$info['meta_tag_values']['twitter_card'] = 'summary';
		endif;

		/**
		 * The Twitter Card Site
		 *
		 */
		if ( $swp_user_options['twitterID'] ) :
			$info['meta_tag_values']['twitter_site'] = '@' . str_replace( '@','',$swp_user_options['twitterID'] );
		endif;

		/**
		 * The Twitter Card Creator
		 */
		if ( $user_twitter_handle ) :
			$info['meta_tag_values']['twitter_creator'] = '@' . str_replace( '@' , '' , $user_twitter_handle );
		endif;

	endif;
	return $info;
}

function swp_twitter_card_html($info) {

	$info['html_output'] .= PHP_EOL . '<meta name="twitter:card" content="'.$info['meta_tag_values']['twitter_card'].'">';
	$info['html_output'] .= PHP_EOL . '<meta name="twitter:title" content="' . trim( $info['meta_tag_values']['twitter_title'] ) . '">';
	$info['html_output'] .= PHP_EOL . '<meta name="twitter:description" content="' . $info['meta_tag_values']['twitter_description'] . '">';
	$info['html_output'] .= PHP_EOL . '<meta name="twitter:image" content="' . $info['meta_tag_values']['twitter_image'] . '">';
	if ( $info['meta_tag_values']['twitter_site'] ) :
		$info['html_output'] .= PHP_EOL . '<meta name="twitter:site" content="' . $info['meta_tag_values']['twitter_site'] . '">';
	endif;
	if ( $info['meta_tag_values']['twitter_creator'] ) :
		$info['html_output'] .= PHP_EOL . '<meta name="twitter:creator" content="' . $info['meta_tag_values']['twitter_creator'] . '">';
	endif;

	return $info;
}

/**
 * Output the CSS for custom selected colors
 *
 * @since  1.4.0
 * @access public
 * @param  array $info The array of information about the post
 * @return array $info The modified array
 */
function swp_output_custom_color( $info ) {

	global $swp_user_options;

	if ( $swp_user_options['dColorSet'] == 'customColor' || $swp_user_options['iColorSet'] == 'customColor' || $swp_user_options['oColorSet'] == 'customColor' ) :
		$info['html_output'] .= PHP_EOL . '<style type="text/css">.nc_socialPanel.swp_d_customColor a, html body .nc_socialPanel.swp_i_customColor .nc_tweetContainer:hover a, body .nc_socialPanel.swp_o_customColor:hover a {color:white} .nc_socialPanel.swp_d_customColor .nc_tweetContainer, html body .nc_socialPanel.swp_i_customColor .nc_tweetContainer:hover, body .nc_socialPanel.swp_o_customColor:hover .nc_tweetContainer {background-color:' . $info['swp_user_options']['customColor'] . ';border:1px solid ' . $info['swp_user_options']['customColor'] . ';} </style>';
	endif;

	if ( $swp_user_options['dColorSet'] == 'ccOutlines' || $swp_user_options['iColorSet'] == 'ccOutlines' || $swp_user_options['oColorSet'] == 'ccOutlines' ) :
		$info['html_output'] .= PHP_EOL . '<style type="text/css">.nc_socialPanel.swp_d_ccOutlines a, html body .nc_socialPanel.swp_i_ccOutlines .nc_tweetContainer:hover a, body .nc_socialPanel.swp_o_ccOutlines:hover a { color:' . $info['swp_user_options']['customColor'] . '; }
.nc_socialPanel.swp_d_ccOutlines .nc_tweetContainer, html body .nc_socialPanel.swp_i_ccOutlines .nc_tweetContainer:hover, body .nc_socialPanel.swp_o_ccOutlines:hover .nc_tweetContainer { background:transparent; border:1px solid ' . $info['swp_user_options']['customColor'] . '; } </style>';

	endif;

	if ( $swp_user_options['floatStyleSource'] == false && ($swp_user_options['sideDColorSet'] == 'customColor' || $swp_user_options['sideIColorSet'] == 'customColor' || $swp_user_options['sideOColorSet'] == 'customColor') ) :
		$info['html_output'] .= PHP_EOL . '<style type="text/css">.nc_socialPanel.swp_d_customColor a, html body .nc_socialPanel.nc_socialPanelSide.swp_i_customColor .nc_tweetContainer:hover a, body .nc_socialPanel.nc_socialPanelSide.swp_o_customColor:hover a {color:white} .nc_socialPanel.nc_socialPanelSide.swp_d_customColor .nc_tweetContainer, html body .nc_socialPanel.nc_socialPanelSide.swp_i_customColor .nc_tweetContainer:hover, body .nc_socialPanel.nc_socialPanelSide.swp_o_customColor:hover .nc_tweetContainer {background-color:' . $info['swp_user_options']['sideCustomColor'] . ';border:1px solid ' . $info['swp_user_options']['sideCustomColor'] . ';} </style>';
	endif;

	if ( $swp_user_options['floatStyleSource'] == false && ( $swp_user_options['sideDColorSet'] == 'ccOutlines' || $swp_user_options['sideIColorSet'] == 'ccOutlines' || $swp_user_options['sideOColorSet'] == 'ccOutlines' ) ) :
		$info['html_output'] .= PHP_EOL . '<style type="text/css">.nc_socialPanel.nc_socialPanelSide.swp_d_ccOutlines a, html body .nc_socialPanel.nc_socialPanelSide.swp_i_ccOutlines .nc_tweetContainer:hover a, body .nc_socialPanel.nc_socialPanelSide.swp_o_ccOutlines:hover a { color:' . $info['swp_user_options']['sideCustomColor'] . '; }
.nc_socialPanel.nc_socialPanelSide.swp_d_ccOutlines .nc_tweetContainer, html body .nc_socialPanel.nc_socialPanelSide.swp_i_ccOutlines .nc_tweetContainer:hover, body .nc_socialPanel.nc_socialPanelSide.swp_o_ccOutlines:hover .nc_tweetContainer { background:transparent; border:1px solid ' . $info['swp_user_options']['sideCustomColor'] . '; } </style>';

		endif;
	return $info;
}

/**
 * Output the CSS to include the icon font.
 *
 * Note: This is done in the header rather than in a CSS file to
 * avoid having the fonts called from a CDN, 95% of which do not
 * support the necessary mime types to render them.
 *
 * @since  1.0.0
 * @access public
 * @param  array  $info An array of information about the post
 * @return array  $info The modified array
 */
function swp_output_font_css( $info = array() ) {
	if ( is_admin() ) :

		// Echo it if we're using the Admin Head Hook
		echo '<style>@font-face {font-family: "sw-icon-font";src:url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.eot?ver=' . SWP_VERSION . '");src:url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.eot?ver=' . SWP_VERSION . '#iefix") format("embedded-opentype"),url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.woff?ver=' . SWP_VERSION . '") format("woff"),
	url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.ttf?ver=' . SWP_VERSION . '") format("truetype"),url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.svg?ver=' . SWP_VERSION . '#1445203416") format("svg");font-weight: normal;font-style: normal;}</style>';
	else :

		// Add it to our array if we're using the frontend Head Hook
		$info['html_output'] .= PHP_EOL . '<style>@font-face {font-family: "sw-icon-font";src:url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.eot?ver=' . SWP_VERSION . '");src:url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.eot?ver=' . SWP_VERSION . '#iefix") format("embedded-opentype"),url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.woff?ver=' . SWP_VERSION . '") format("woff"), url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.ttf?ver=' . SWP_VERSION . '") format("truetype"),url("' . SWP_PLUGIN_URL . '/fonts/sw-icon-font.svg?ver=' . SWP_VERSION . '#1445203416") format("svg");font-weight: normal;font-style: normal;}</style>';

		return $info;
	endif;
}
